### ISSUE TITLE
Serve a zip file without creating another zip?

### ISSUE THREAD

**Issue by mkraha** [maennchen/ZipStream-PHP#148]
Hello, How to serve a zip file(which is already created on pc) without creating another zip. ?

**Comment by NicolasCARPi** [comment]
Hello,

I'm not sure I understand your question, but if you want to serve a zip file, you can use something like https://symfony.com/doc/current/components/http_foundation.html#streaming-a-response to stream it. But you should not use PHP-ZipStream, because it's a zip library and if you don't want to zip something you should not use it!

**Comment by mkraha** [comment]
Ok Thank you.
