### ISSUE TITLE
 saving files back to  aws s3

### ISSUE THREAD

**Issue by aseemagarwal123** [maennchen/ZipStream-PHP#157]
want to send the zip file back to s3 is there any way of doing that using this library
dont want the file in the php output stream rather than want to upload it to aws s3

**Comment by maennchen** [comment]
Seems to have problems with GitHub, content from the edit history:

## Code

```php
  public function __construct()
    {
        $client = new S3Client([  
			'key'    => ''
			'secret' => ''
			'version' =>'latest',
			'region' => ''
		]);

        $client->registerStreamWrapper();
        
        $this->largeFileMethod = Method::STORE();
        //$this->outputStream = fopen('php://output', 'wb');
       $this->outputStream = fopen('s3://subu-test/aseem/ex4.zip', 'a');
      
    }
```

## Informations

* ZipStream-PHP version: `2.1`
* PHP version: `7.2`

Please include any supplemental information you deem relevant to this issue.

**Comment by maennchen** [comment]
@aseemagarwal123 

The code you posted does not show the code needed to reproduce the issue. Please post the complete code needed to reproduce the issue.

PS1: PHP 7.2 is no longer actively supported, please update
PS2: Can you please test this using a file stream as the output stream instead of S3 since we're not able to support the S3 client itself.

**Comment by aseemagarwal123** [comment]
its solved thank you
