### ISSUE TITLE
PHP 5.6 Support

### ISSUE THREAD

**Issue by aseemagarwal123** [maennchen/ZipStream-PHP#159]

**Comment by maennchen** [comment]
We only support actively supported PHP versions.

You can either use old versions of this library or adapt it so that it works with PHP 5.6.

This will however mean that we will not support it if there's any issues and we will not provide bug fixes / security fixes etc.

I strongly recommend to update to at least PHP 7.3: https://www.php.net/supported-versions.php

**Comment by aseemagarwal123** [comment]
updating is not an option right now and can you suggest which versions of your library  i can use with php 5.6

**Comment by maennchen** [comment]
As I said we don't support old versions. Therefore you'll have to figure out this one yourself.
