### ISSUE TITLE
2021-01-01 - Remove PHP 7.2

### ISSUE THREAD

**Issue by maennchen** [maennchen/ZipStream-PHP#166]
# Description of the problem

On 1. of January 2021 PHP 7.2 is EOL. Change the requirement in the `composer.json` and remove it from Travis.

* [ ] Require PHP 7.3 in `composer.json`
* [x] Remove `7.2` from CI Workflow

**Comment by pieterdt** [comment]
if PHP 7 is required, what about the remark in ZipStream.php:
```
// incremental compression with deflate_add
// makes this second read unnecessary
// but it is only available from PHP 7.0
```
I'm willing to look into refactoring this so that the rewind can be avoided and zipstream could probably work on S3 streams even without the zeroheader. Is my understanding correct (before I make an attempt to deeply understand the process that is currently implemented)?

**Comment by maennchen** [comment]
@pieterdt This is quite a long time ago. Therefore I'm not sure...

I'd appreciate if you would take the time and simplify things where possible 🙂

**Comment by pieterdt** [comment]
after making a better attempt at understanding that part of the code: it is indeed safe to remove it. I will make a PR on a new ticket. But it will not be possible to avoid rewinds when not setting the zero-header, at least as far as I could tell.

**Comment by Froxz** [comment]
Hi @maennchen 

there is also issue with: `myclabs/php-enum ^1.5` (satisfiable by myclabs/php-enum[1.8.0])

But their requirement is php-7.3.
