### ISSUE TITLE
Deprecate all the removed/changed code changes v2 => v3

### ISSUE THREAD

**Issue by Chris53897** [maennchen/ZipStream-PHP#275]
### Description

Hi. It would be great to deprecate all changes from https://github.com/maennchen/ZipStream-PHP#upgrade-to-version-300 in Version 2.

Example:
Add in class docbloc @deprecated Use xxx instead
https://github.com/maennchen/ZipStream-PHP/blob/v2/src/Option/Archive.php

Or trigger real deprecation notices.

That helps people to get a migration path they are used to.
The IDE will now warn you.
I was surprised today that our code does not work anymore (after a update from 2 => 3) without any deprecation message from version2.

**Comment by maennchen** [comment]
A deprecation normally means that should use X instead of Y (both part of the same release / version)

It does not make sense to me to deprecate stuff in v2 as long as there’s no replacement api in v2 as well.

The version indicates a major update and there’s a note on the changes. That should be sufficient IMO.
