### ISSUE TITLE
Resulting Zip can't be extracted in Mac OSX Archive Utility and Windows WinRAR

### ISSUE THREAD

**Issue by danielforer** [maennchen/ZipStream-PHP#49]
I'm using Zipstream to create a streamed zip download to browser in a Symfony 2.8 + PHP 7 on Ubuntu web application. Files are streamed from AWS s3 bucket via aws-sdk-php which I used to create an S3Client with valid credentials against which I register the stream wrapper (s3Client->registerStreamWrapper();). 

In web interface, user clicks "Download" button which initiates the above and a zip downloads via browser to user's local machine. However, the zip cannot be opened by:

-  Archive Utility (native app) on Mac OSX (El Capitan) with error "Unable to extract 'test.zip'. Error 2 No such file or directory.)
- WinRAR on Windows with error "Archive is corrupted".

I can open the file via 7-zip on Windows and TheUnarchiver on Mac, but this is not a suitable solution as users can't be expected to guess or know to download a specific third party archive application to make a downloaded zip file usable.

I have seen a previous issue related to this from a few years ago requiring other third party bundles be updated and a related SO post (https://stackoverflow.com/questions/5573211/dynamically-created-zip-files-by-zipstream-in-php-wont-open-in-osx) dealing with the same issue back in 2011. I have updated my bundles and attempted the suggestions in that SO post to fix the issue without success.

Sample Code:

```php
    //$s3Client instantiated with valid credentials and passed to function 
    $this->s3Client = $s3Client;  
    $this->s3Client->registerStreamWrapper();

$opt = array(
            'comment' => 'test zip file.',
            'content_type' => 'application/octet-stream'
          );
    $zip = new ZipStream\ZipStream($filename, $opt);

/*
    simple case with simple test file.
 */

    $keys = array(
          "zipsimpletestfolder/file1.txt"
      );

    foreach ($keys as $key) {
        // Get the file name in S3 key so we can save it to the zip file 
        // using the same name.
        $fileName = basename($key);

        $bucket = 'mg-test';

        $s3path = "s3://" . $bucket . "/" . $key;

        if ($streamRead = fopen($s3path, 'r')) {
          $zip->addFileFromStream($fileName, $streamRead);        
        } else {
          die('Could not open stream for reading');
        }
    }
```

In ZipStream class I see the following version settings for making and extract:

```php
   ...

   // build file header
		$fields = array( // (from V.A of APPNOTE.TXT)
			array(
				'V',
				0x04034b50
			), // local file header signature
			array(
				'v',				
				0x000A //(6 << 8) + 3)
			), // version needed to extract
			//FIXED as mentioned in http://linlog.skepticats.com/entries/2012/02/Streaming_ZIP_files_in_PHP.php
			//and http://stackoverflow.com/questions/5573211/dynamically-created-zip-files-by-zipstream-in-php-wont-open-in-osx

  ...

```

Can you please assist with solving this issue?

**Comment by martynenko-dmitry** [comment]
Здравствуйте .

Я нахожусь в отпуске до 23.06 и не могу вам ответить.
По техническим вопросам пишите на vadim.k@realt.by, по организационным
на info@realt.by

DF> I'm using Zipstream to create a streamed zip download to browser
DF> in a Symfony 2.8 + PHP 7 on Ubuntu web application. Files are
DF> streamed from AWS s3 bucket via aws-sdk-php which I used to create
DF> an S3Client with valid credentials against which I register the
DF> stream wrapper (s3Client->registerStreamWrapper();).
DF>  In web interface, user clicks "Download" button which initiates
DF> the above and a zip downloads via browser to user's local machine.
DF> However, the zip cannot be opened by:
DF>   Archive Utility (native app) on Mac OSX (El Capitan) with error
DF> "Unable to extract 'test.zip'. Error 2 No such file or directory.)
DF> WinRAR on Windows with error "Archive is corrupted". 
DF>  I can open the file via 7-zip on Windows and TheUnarchiver on
DF> Mac, but this is not a suitable solution as users can't be
DF> expected to guess or know to download a specific third party
DF> archive application to make a downloaded zip file usable.
DF>  I have seen a previous issue related to this from a few years
DF> ago requiring other third party bundles be updated and a related
DF> SO post
DF> (https://stackoverflow.com/questions/5573211/dynamically-created-zip-files-by-zipstream-in-php-wont-open-in-osx)
DF> dealing with the same issue back in 2011. I have updated my
DF> bundles and attempted the suggestions in that SO post to fix the issue without success.
DF>  Sample Code:
DF>  `
DF> //$s3Client instantiated with valid credentials and passed to function
$this->>s3Client = $s3Client;
$this->>s3Client->registerStreamWrapper();
DF>  $opt = array(
'comment' =>> 'test zip file.',
'content_type' =>> 'application/octet-stream'
DF> );
DF> $zip = new ZipStream\ZipStream($filename, $opt);
DF>  /*
DF> simple case with simple test file.
DF> */
DF>  $keys = array(
DF>       "zipsimpletestfolder/file1.txt"
DF>   );

DF> foreach ($keys as $key) {
DF>     // Get the file name in S3 key so we can save it to the zip file 
DF>     // using the same name.
DF>     $fileName = basename($key);

DF>     $bucket = 'mg-test';

DF>     $s3path = "s3://" . $bucket . "/" . $key;

DF>     if ($streamRead = fopen($s3path, 'r')) {
DF>       $zip->addFileFromStream($fileName, $streamRead);        
DF>     } else {
DF>       die('Could not open stream for reading');
DF>     }
DF> }

DF>  `
DF>  In ZipStream class I see the following version settings for making and extract:
DF>  `
DF> ...
DF>  // build file header
DF> $fields = array( // (from V.A of APPNOTE.TXT)
DF> array(
DF> 'V',
DF> 0x04034b50
DF> ), // local file header signature
DF> array(
DF> 'v',
DF> 0x000A //(6 << 8) + 3)
DF> ), // version needed to extract
DF> //FIXED as mentioned in
DF> http://linlog.skepticats.com/entries/2012/02/Streaming_ZIP_files_in_PHP.php
DF> //and
DF> http://stackoverflow.com/questions/5573211/dynamically-created-zip-files-by-zipstream-in-php-wont-open-in-osx
DF>  ...
DF>  `
DF>  Can you please assist with solving this issue?
DF> —
DF> You are receiving this because you are subscribed to this thread.
DF> Reply to this email directly, view it on GitHub, or mute the thread.
DF>   
DF>     
DF> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/maennchen/ZipStream-PHP","title":"maennchen/ZipStream-PHP","subtitle":"GitHub
DF> repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open
DF> in
DF> GitHub","url":"https://github.com/maennchen/ZipStream-PHP"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Resulting
DF> Zip can't be extracted in Mac OSX Archive Utility and Windows
DF> WinRAR (#49)"}],"action":{"name":"View
DF> Issue","url":"https://github.com/maennchen/ZipStream-PHP/issues/49"}}}



-- 
C наилучшими пожеланиями,
Интернет центр "Realt.by - Недвижимость"
Дмитрий Мартыненко

тел:      +375 29 679-77-75
mailto: dima@realt.by
skype: dmitry-martynenko
www: http://realt.by

**Comment by maennchen** [comment]
Does it work if you add the file using the `addFile` or `addFileFromPath` method?

**Comment by martynenko-dmitry** [comment]
Здравствуйте .

Я нахожусь в отпуске до 23.06 и не могу вам ответить.
По техническим вопросам пишите на vadim.k@realt.by, по организационным
на info@realt.by

JM> Does it work if you add the file using the addFileor addFileFromPathmethod?
JM> —
JM> You are receiving this because you commented.
JM> Reply to this email directly, view it on GitHub, or mute the thread.
JM>   
JM>     
JM> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/maennchen/ZipStream-PHP","title":"maennchen/ZipStream-PHP","subtitle":"GitHub
JM> repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open
JM> in
JM> GitHub","url":"https://github.com/maennchen/ZipStream-PHP"}},"updates":{"snippets":[{"icon":"PERSON","message":"@maennchen
JM> in #49: Does it work if you add the file using the `addFile` or
JM> `addFileFromPath` method?"}],"action":{"name":"View
JM> Issue","url":"https://github.com/maennchen/ZipStream-PHP/issues/49#issuecomment-310379492"}}}



-- 
C наилучшими пожеланиями,
Интернет центр "Realt.by - Недвижимость"
Дмитрий Мартыненко

тел:      +375 29 679-77-75
mailto: dima@realt.by
skype: dmitry-martynenko
www: http://realt.by

**Comment by maennchen** [comment]
@martynenko-dmitry

⚠️  **Deactivate your auto-reply or I will ban you from seeing this repository.** ⚠️

**Comment by martynenko-dmitry** [comment]
Здравствуйте .

Я нахожусь в отпуске до 23.06 и не могу вам ответить.
По техническим вопросам пишите на vadim.k@realt.by, по организационным
на info@realt.by

JM> @martynenko-dmitry
JM>  ⚠️Deactivate your auto-reply or I will ban you from seeing this repository. ⚠️
JM> —
JM> You are receiving this because you were mentioned.
JM> Reply to this email directly, view it on GitHub, or mute the thread.
JM>   
JM>     
JM> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/maennchen/ZipStream-PHP","title":"maennchen/ZipStream-PHP","subtitle":"GitHub
JM> repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open
JM> in
JM> GitHub","url":"https://github.com/maennchen/ZipStream-PHP"}},"updates":{"snippets":[{"icon":"PERSON","message":"@maennchen
JM> in #49: @martynenko-dmitry\r\n\r\n⚠️  **Deactivate your auto-reply
JM> or I will ban you from seeing this repository.** ⚠️
JM> "}],"action":{"name":"View
JM> Issue","url":"https://github.com/maennchen/ZipStream-PHP/issues/49#issuecomment-310379961"}}}



-- 
C наилучшими пожеланиями,
Интернет центр "Realt.by - Недвижимость"
Дмитрий Мартыненко

тел:      +375 29 679-77-75
mailto: dima@realt.by
skype: dmitry-martynenko
www: http://realt.by

**Comment by danielforer** [comment]
@maennchen I just tried with addFile and zip downloads and can be extracted on Mac OSX via Archive Utility.

`
       $fileName = basename($key);
       $bucket = 'mg-test';
       $s3path = "s3://" . $bucket . "/" . $key;

       $zip->addFile($fileName, $s3path);
`

**Comment by martynenko-dmitry** [comment]
Здравствуйте .

Я нахожусь в отпуске до 23.06 и не могу вам ответить.
По техническим вопросам пишите на vadim.k@realt.by, по организационным
на info@realt.by

DF> @maennchenI just tried with addFile and zip downloads and can be
DF> extracted on Mac OSX via Archive Utility.
DF>  `
DF> $fileName = basename($key);
DF> $bucket = 'mg-test';
DF> $s3path = "s3://" . $bucket . "/" . $key;
DF>  $zip->addFile($fileName, $s3path);

DF>  `
DF> —
DF> You are receiving this because you were mentioned.
DF> Reply to this email directly, view it on GitHub, or mute the thread.
DF>   
DF>     
DF> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/maennchen/ZipStream-PHP","title":"maennchen/ZipStream-PHP","subtitle":"GitHub
DF> repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open
DF> in
DF> GitHub","url":"https://github.com/maennchen/ZipStream-PHP"}},"updates":{"snippets":[{"icon":"PERSON","message":"@danielforer
DF> in #49: @maennchen I just tried with addFile and zip downloads and
DF> can be extracted on Mac OSX via Archive Utility.\r\n\r\n`\r\n     
DF> $fileName = basename($key);\r\n       $bucket = 'mg-test';\r\n    
DF> $s3path = \"s3://\" . $bucket . \"/\" . $key;\r\n\r\n      
DF> $zip-\u003eaddFile($fileName,
DF> $s3path);\r\n`"}],"action":{"name":"View
DF> Issue","url":"https://github.com/maennchen/ZipStream-PHP/issues/49#issuecomment-310382784"}}}



-- 
C наилучшими пожеланиями,
Интернет центр "Realt.by - Недвижимость"
Дмитрий Мартыненко

тел:      +375 29 679-77-75
mailto: dima@realt.by
skype: dmitry-martynenko
www: http://realt.by

**Comment by maennchen** [comment]
@martynenko-dmitry

I've blocked you from posting any new comments. As soon as you have fixed the issue, you can write me an email and I will unblock you.

Please make sure to never do something like that. I hope you're only spamming my repository at the moment.

**Comment by maennchen** [comment]
@danielforer To correctly quote code, you have to put 3 ticks before and after.

**Comment by maennchen** [comment]
@danielforer 

Hmm. Can you provide me with a test zip?

Chances are good, that the Archive Utility Once More doesn't support the full zip spec and the file is correct. If that is the case, we can't do more than to write a warning about that in the docs.

**Comment by danielforer** [comment]
Zip attached as created by addFileFromStream.
[test.zip](https://github.com/maennchen/ZipStream-PHP/files/1094958/test.zip)

It was my thought before posting the issue that Archive Utility but I am be no means a zip spec pro.

**Comment by danielforer** [comment]
Just to re-iterate, their is also an issue with the downloaded zip on Windows when trying to open with WinRaR: it says file is corrupted. 7-Zip on Windows could handle it. So it not just isolated to Archive Utility.

**Comment by maennchen** [comment]
@danielforer Open the ZIP with a Text-Editor :P

It is a wonder that 7-ZIP can open it.

**Comment by danielforer** [comment]
Are you telling me the download is actually a text file containing hex values with a .zip extension?

**Comment by maennchen** [comment]
It contains a PHP error. (HTML Code)

![screen shot 2017-06-22 at 15 22 43](https://user-images.githubusercontent.com/333918/27442036-ae90db46-575e-11e7-85bd-ec06c70c1710.png)

**Comment by maennchen** [comment]
Can you please verify that this solves the issue?

**Comment by danielforer** [comment]
Doh! The response is sending html response in the zip stream. Yeah, I think its how i'm handling the response in symfony with ZipStream also firing off the download. Yeah will verify issue is solved this side.

Thanks for the assistance & great response (excuse the pun).

**Comment by danielforer** [comment]
Just to help anyone with this if trying to use ZipStream in a Symfony Controller Action, this is what I did:
```
/**
 * @Route("/zipstream", name="zipstream")
 */
public function zipStreamAction()
{
    //test file on s3
    $s3keys = array(
      "ziptestfolder/file1.txt"
    );

    $s3Client = $this->get('app.amazon.s3'); //s3client service
    $s3Client->registerStreamWrapper(); //required

    $response = new StreamedResponse(function() use($s3keys, $s3Client) 
    {

        // Define suitable options for ZipStream Archive.
        $opt = array(
                'comment' => 'test zip file.',
                'content_type' => 'application/octet-stream'
              );
        //initialise zipstream with output zip filename and options.
        $zip = new ZipStream\ZipStream('test.zip', $opt);

        //loop keys useful for multiple files
        foreach ($s3keys as $key) {
            // Get the file name in S3 key so we can save it to the zip 
            //file using the same name.
            $fileName = basename($key);

            //concatenate s3path.
            $bucket = 'bucketname';
            $s3path = "s3://" . $bucket . "/" . $key;        

            //addFileFromStream
            if ($streamRead = fopen($s3path, 'r')) {
              $zip->addFileFromStream($fileName, $streamRead);        
            } else {
              die('Could not open stream for reading');
            }
        }

        $zip->finish();

    });

    return $response;
}
```

**Comment by maennchen** [comment]
@danielforer I'd be happy to accept a Doc PR with a Mardown File containing that. Would you be interested to create one?

**Comment by danielforer** [comment]
@maennchen yeah, I'm happy to contribute that.
