### ISSUE TITLE
bad CRC error while trying to decompress zip created with ZipStream

### ISSUE THREAD

**Issue by ilex** [maennchen/ZipStream-PHP#65]
I use the `addFileFromStream` to create archive. Archive is created but when I tried to extract it (using console linux `unzip` or GUI `Archive Manager` and GUI program for Windows) it fails with wrong crc error while extracting file.
It seems that pull request #61 fix this problem as I tried it locally by patching lib and it worked - I could extract files.

**Comment by ilex** [comment]
I also have another crc issue with `addFileFromStream`. It works fine for local files but when I use `fopen` for remote files (the same ones but through http) i have a crc error. I use a script like this to test:
```php
<?php

require_once 'vendor/autoload.php';

use ZipStream\ZipStream;

$zipPath = '/tmp/file.zip';

$inputFile = fopen('http://localhost/data/test.txt', 'rb');
/* $inputFile = fopen('data/test.txt', 'rb'); */

$fd = fopen($zipPath, 'w');
try {
    $zip = new ZipStream('output.zip', [
        ZipStream::OPTION_OUTPUT_STREAM => $fd,
    ]);

    $zip->addFileFromStream('data/test.txt', $inputFile);
    $zip->finish();
}
finally {
    fclose($fd);
}
system("unzip -t $zipPath");
unlink($zipPath);
``` 
For method `store` archive is created fine for remote file and for local one but for `deflate` in remote case i have a crc error. I try to investigate a bit and output `$crc`, `$len`, `$zlen` for both remote and local cases:
Local file:
```
crc: 1759459390
len: 44206
zlen: 40324
```
Remote file:
```
crc: 1759459390
len: 44206
zlen: 41239
```
It seems that `zlen` is different so `zdata` is different too..

**Comment by Petah** [comment]
I also get this problem using `s3` streams.

**Comment by freekmurze** [comment]
> I also get this problem using s3 streams.
Me too!

**Comment by maennchen** [comment]
If someone comes up with a solution, I'll happily review & merge it. I've currently no time myself to investigate the issue though. Sorry :(

**Comment by maennchen** [comment]
There has been a bigger refactoring of the library. COuld you verify if this problem still exists?

**Comment by NicolasCARPi** [comment]
I can reproduce this issue with php 7.2.8 on GNU/Linux and unzip 6.0 with 1.0.0-alpha1. Tested local file, http and https (with redirects).

The issue only appears with remote files, like @ilex remarked. Something missing from this issue is the error message:

`PHP Warning:  rewind(): stream does not support seeking in /home/a/project/vendor/maennchen/zipstream-php/src/DeflateStream.php on line 19`

Now if we go digging in the stack, in [File.php line 337](https://github.com/maennchen/ZipStream-PHP/blob/master/src/File.php#L337) we find that the processStreamWithComputeHeader is called. And if we set the ZeroHeader to true, the crc errors are gone.

So the answer to this issue might just be a configuration flag that must be set. Here is the script I used with the working configuration:

~~~php
<?php

require_once 'vendor/autoload.php';

use ZipStream\ZipStream;
use ZipStream\Option\Archive as ArchiveOptions;

$zipPath = '/tmp/file.zip';

// this works always
//$inputFile = fopen('test.txt', 'rb');
// this doesn't work withouth the zeroheader option
$inputFile = fopen('https://get.elabftw.net/updates.ini', 'rb');

$fd = fopen($zipPath, 'w');
try {
    // note the new syntax for 1.0.0
    $opt = new ArchiveOptions();
    $opt->setOutputStream($fd);
    // this is the line that solves the issue
    $opt->setZeroHeader(true);

    // rest is the same as OP's script
    $zip = new ZipStream('output.zip', $opt);

    $zip->addFileFromStream('zippedfile', $inputFile);
    $zip->finish();
}
finally {
    fclose($fd);
}
system("unzip -t $zipPath");
unlink($zipPath);
~~~

**Comment by maennchen** [comment]
Closed because of inactivity.
