### ISSUE TITLE
Create Directories

### ISSUE THREAD

**Issue by dotriz** [maennchen/ZipStream-PHP#78]
I know how we can add files in folders and sub-folders in a zip. But is it possible to add blank folders?

I want to allow users to download their data in zip and want to match exactly same structure as they have on web, so creating lank folders is important.

**Comment by NicolasCARPi** [comment]
Hello @dotriz,

You can do like that to create and empty directory (with version 1.0.0-alpha):

~~~php
$zip->addFile('directory/', '');
~~~

**Comment by dotriz** [comment]
Any plan to add this support in previous versions?

**Comment by NicolasCARPi** [comment]
It doesn't work in previous versions?

**Comment by maennchen** [comment]
@NicolasCARPi We should probably add a new function `createDirectory` that does this. This seems like a hack to me.

I would add the function to the v1 versions only.

**Comment by dotriz** [comment]
@NicolasCARPi that's correct, it doesn't work on previous versions.

**Comment by ethanzway** [comment]
@NicolasCARPi 
`$zip->addFile('directory/', '');`
this works fine in linux but not work in windows if you don't add other file in the directory.
when you decompress the zip it will be a blank file other than a directory.

**Comment by claytron5000** [comment]
I came here looking for this. I basically want to replace the PHP standard ZipArchive with this so that I can build and stream directly to s3. Our current implementation using ZipArchive uses the addEmptyDir. 

I don't know if this is too ambitious, but something like a drop-in replacement for ZipArchive would be awesome. Maybe this should be a different issue.

https://www.php.net/manual/en/class.ziparchive.php

**Comment by gocontractdev** [comment]
I have faced the same issue creating empty folders fails except if using what @NicolasCARPi suggested:

$zip->addFile($directory . DIRECTORY_SEPARATOR, '');

However, testing the download of a zipStream causes unit test failure since **_it counts empty folders created this way as a file_**: 

$zip = new ZipArchive();
$zip->open($tempName); // open the downloaded stream
 self::assertEquals($expectedFilesCount, $zip->count); // count is incorrect -- it counts folders as file

this counts extra for each folder which is totally wrong also happens for $zip

**Comment by christian-kolb** [comment]
@maennchen Help wanted, means a pull request for it would be merged?  🙂

**Comment by maennchen** [comment]
@christian-kolb a PR is very welcome 🙂

**Comment by christian-kolb** [comment]
@maennchen I started and saw pretty quickly that I severely underestimated the complexity of what this library and what is needed to make this change. The whole directory construct doesn't seem to exist in the package yet.
My approach would be to create a `Directory` class according to the structure of the `File` class. But I'm not sure if the concepts match here. A directory doesn't have a content but is more of a marker. I'm pretty much lost as soon as it comes to the headers and the `V...` format. Can you point me to relevant documentation? Then I would try to pickup from there 🙂

**Comment by maennchen** [comment]
@christian-kolb Yeah, it's not that approachable.

For every change, I also have to read the specifications.

https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT

Unfortunately, I also do not know about resources that are a lot better...

**Comment by bastien70** [comment]
Hello, what's about this feature ?

**Comment by maennchen** [comment]
@bastien70 A PR would be welcome.

**Comment by bastien70** [comment]
I don't have the capacity to do that kind of PR sorry.

**Comment by maennchen** [comment]
@bastien70 And I do not have the time. If this is important to anyone, please open a PR. Otherwise there will be no solution to this anytime soon.

**Comment by walkingCommiter** [comment]
@bastien70  If it is okay for your customers I would suggest a simple solution to just putting an empty file in all empty folders by default to keep the structure (kind of like how .gitignore works for git folders) and just waiting for maintainers to see what we can do.

**Comment by maennchen** [comment]
Tracked in #224

**Comment by ahmed-bhs** [comment]
@maennchen any new about this feature ?

**Comment by maennchen** [comment]
@ahmed-bhs This feature is part of the current beta release.

**Comment by ahmed-bhs** [comment]
Hey @maennchen 3.0.0@beta ? Does there any documentation behind the feature?

**Comment by maennchen** [comment]
@ahmed-bhs The docs are not published right now.

You can checkout the project and generate the docs. (composer run docs:generate)

Otherwise everything is documented in the code comments.

https://github.com/maennchen/ZipStream-PHP/blob/815cf35e8f5285ee91ff97403953519903b3d6f4/src/ZipStream.php#L475
